### ISSUE TITLE
Update USDC on Arbitrum One network

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-ChainList#141]
**Describe the task**
Update USDC on Arbitrum One network

The info of USDC on Arbitrum One in Extension is out of date.
It update with name is Bridged USDC and symbol is USDC.e.

Now, Arbitrum One network have native USDC with contract address is `0xaf88d065e77c8cC2239327C5EDb3A432268e5831`.

**Comment by NamPhamc99** [comment]
- [ ] Find different USDC on Arbitrum Network, why are there many USDC?
- [ ] Update USDC information accordingly

**Comment by bluezdot** [comment]
- Arbitrum One supports two types of USDC: 
    - Arbitrum-native USDC (USDC): its native USDC
    - Bridged USDC (USDC.e): A bridged form of Ethereum-native USDC on Arbitrum blockchains, transferred via the Avalanche Bridge.
- The key difference is that USDC.e is not directly supported by Circle's products. This means you can't deposit it into a Circle account to convert it back to fiat currency directly. To do so, you would need to "unbridge" the USDC.e back to Ethereum-native USDC, then deposit it into a Circle Account for conversion to fiat.
- The reason why there are two types of USDC as above is that since its formation, Arbitrum One has supported Bridged USDC from other chains. On June 8th, Circle supports direct minting and burning of Arbitrum-native USDC. Therefore, Bridged USDC was renamed from USDC -> USDC.e and the Arbitrum-native USDC is USDC.

Ref: 
1. https://docs.arbitrum.io/bridge-tokens/concepts/usdc-concept
2. https://www.datawallet.com/crypto/usdc-e-vs-usdc-explained

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/FZdYsBEEqrHQckY

Validation passed in case update token
![image](https://github.com/Koniverse/SubWallet-ChainList/assets/130966515/e204de89-bbb5-483f-8244-2bd913437047)

Notes: Check the case update token in token list to fiat-onramp in http://14.224.158.246:8900/s/gnqg2coGDJMDeEb
